{% set name = "kepmodel" %}
{% set version = "1.0.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kepmodel-{{ version }}.tar.gz
  sha256: 9f4097c18fc1fda1f6cd8b320ea4488c1704a478042d4382062400acb477c7dd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=61.0    
  run:
    - kepderiv >=1.0
    - numpy >=1.16
    - python >=3.8
    - scipy >=1.2
    - spleaf >=2.0

test:
  imports:
    - kepmodel
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.unige.ch/delisle/kepmodel
  summary: Keplerian system model.
  license: EUPL-1.2
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jbdelisle
